apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "studentdb"
        - name: MYSQL_USER
          value: "student"
        - name: MYSQL_PASSWORD
          value: "student"
