apiVersion: v1
kind: Namespace
metadata:
  name: sonar

---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: sonar
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30090
  selector:
    app: sonarqube

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: sonarqube
          image: sonarqube:lts-community
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
              value: "true"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: sonar-data
              mountPath: /opt/sonarqube/data
            - name: sonar-logs
              mountPath: /opt/sonarqube/logs
      volumes:
        - name: sonar-data
          emptyDir: {}
        - name: sonar-logs
          emptyDir: {}
